name: nova_chat_ai
description: Nova Chat AI
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  path_provider: ^2.1.0
  video_player: ^2.8.0
  shared_preferences: ^2.2.0
  flutter_tts: ^4.2.0
flutter:
  uses-material-design: true
